name: ttk4265
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - spectral
  - scipy
  - jupyter
  - scikit-learn
  - scikit-image
